### ISSUE TITLE
Could you provide an example flow?

### ISSUE THREAD

**Issue by pinanunes** [inNETMonitoring/node-red-contrib-R-nodes#1]
This is a node with great potential!
Could you provide an example flow?
Would it be possible to export a node with included R code as a node?

**Comment by pinanunes** [comment]
Got it working! Still, an example of a simple flow would help.
Great node!

**Comment by mblaettler** [comment]
Hi pinanunes

Thanks for your feedback. I'm glad you got it working. We'll upload an example flow sometime next week.

It is not planed that you can export a node with R code as a separate node. In case you need the same R-Code on different occasions I'd recommend you to store the R-Code as a script on your R-Server and just execute this script within the node.

**Comment by mblaettler** [comment]
I uploaded a simple example flow to the [flow repository](https://flows.nodered.org/flow/96b312540d537d708eb4d35b94684c42).
