### ISSUE TITLE
unable to install on palette manager and docker CLI

### ISSUE THREAD

**Issue by brunoamaral** [inNETMonitoring/node-red-contrib-R-nodes#2]
For some reason I can't find this module through the usual GUI for Node-Red and trying to install through the command line returns a 404 error.

Is there any way I can help fix this?

**Comment by mblaettler** [comment]
Hi @brunoamaral  

We have no issues in installing the package via CLI. Which module returns a 404 error? You might need to install the build-tools if you're using Windows. See [this package](https://www.npmjs.com/package/windows-build-tools).

Thanks for the hint about the package not being installable through the usual GUI. We will take care of it on our next update.

**Comment by brunoamaral** [comment]
Hello @mblaettler ! 🙂 

I followed the instructions on the readme but it didn't find the module. Eventually, I pointed npm directly to this repository and it worked as expected.
